#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

#define AUDIO_INPUT_SAMPLE_RATE  24000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000

#define AUDIO_INPUT_REFERENCE    true

#define AUDIO_I2S_GPIO_MCLK GPIO_NUM_2
#define AUDIO_I2S_GPIO_WS GPIO_NUM_45
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_17
#define AUDIO_I2S_GPIO_DIN  GPIO_NUM_16
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_15

#define AUDIO_CODEC_PA_PIN       GPIO_NUM_46
#define AUDIO_CODEC_I2C_SDA_PIN  GPIO_NUM_8
#define AUDIO_CODEC_I2C_SCL_PIN  GPIO_NUM_18
#define AUDIO_CODEC_ES8311_ADDR  ES8311_CODEC_DEFAULT_ADDR
#define AUDIO_CODEC_ES7210_ADDR  ES7210_CODEC_DEFAULT_ADDR

#define BUILTIN_LED_GPIO        GPIO_NUM_4
#define BOOT_BUTTON_GPIO        GPIO_NUM_0
#define VOLUME_UP_BUTTON_GPIO   GPIO_NUM_12
#define VOLUME_DOWN_BUTTON_GPIO GPIO_NUM_11


//#define DISPLAY_I2C_SDA_PIN GPIO_NUM_6
//#define DISPLAY_I2C_SCL_PIN GPIO_NUM_7

#define POWER_BUTTON_GPIO GPIO_NUM_41    // Power/Main Key Detect 0: Press
#define POWER_CONTROL_GPIO GPIO_NUM_38   // Power Ctrl, 1: Power On
//#define POWER_LCD_CTRL_GPIO GPIO_NUM_10  // LCD Ctrl, 1: Power On, default: Power On
#define POWER_AUDIO_CTRL_GPIO GPIO_NUM_39 // Audio Ctrl, 1: Power On, default: Power On

//#define LED_RGB_PWM_GPIO GPIO_NUM_4
#define SHOCK_DETECT_GPIO GPIO_NUM_40       // Shock Detect 0: Shock
#define BATTERY_LEVEL_GPIO GPIO_NUM_5

#define CHARGING_DETECT_GPIO GPIO_NUM_21    // Charging Detect 0: Charging


//#define DISPLAY_WIDTH   128
//#define DISPLAY_HEIGHT  64
//#define DISPLAY_MIRROR_X true
//#define DISPLAY_MIRROR_Y true


#endif // _BOARD_CONFIG_H_
